# Environment: Development
cluster_name        = "meracommerce-dev"
region              = "us-east-1"
namespace           = "customer-ns"
service_account     = "customer-sa"
node_instance_type  = "t3.medium"
node_desired        = 2
node_min            = 1
node_max            = 3
